// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Banner from "./islands/Banner.tsx";
import * as $CustomCarousel from "./islands/CustomCarousel.tsx";
import * as $Faq_item from "./islands/Faq-item.tsx";
import * as $HoursOfOperation from "./islands/HoursOfOperation.tsx";
import * as $ImageWithParagraph from "./islands/ImageWithParagraph.tsx";
import * as $Teste from "./islands/Teste.tsx";
import * as $TitleSection from "./islands/TitleSection.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Banner.tsx": $Banner,
    "./islands/CustomCarousel.tsx": $CustomCarousel,
    "./islands/Faq-item.tsx": $Faq_item,
    "./islands/HoursOfOperation.tsx": $HoursOfOperation,
    "./islands/ImageWithParagraph.tsx": $ImageWithParagraph,
    "./islands/Teste.tsx": $Teste,
    "./islands/TitleSection.tsx": $TitleSection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
