// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Banner from "./islands/Banner.tsx";
import * as $HoursOfOperation from "./islands/HoursOfOperation.tsx";
import * as $Teste from "./islands/Teste.tsx";
import * as $lucide_icon from "./islands/lucide-icon.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Banner.tsx": $Banner,
    "./islands/HoursOfOperation.tsx": $HoursOfOperation,
    "./islands/Teste.tsx": $Teste,
    "./islands/lucide-icon.tsx": $lucide_icon,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
